### ISSUE TITLE
You may see there is warning for render list

### ISSUE THREAD

**Issue by chucklien** [ritata/react-practice#1]
https://github.com/ritata/react-practice/blob/18206507ece5473f6a85b5d6962664ffd1cbe118/src/App.js#L23

You could check following link
https://zh-hant.reactjs.org/docs/lists-and-keys.html#basic-list-component

When you render a list, need to remember add `key` for children.

But it will be discussed in the future chapter, just keep in mind.

**Comment by ritata** [comment]
Thanks for your reminder, the issue has been fixed.
Please refer this pull request:
https://github.com/ritata/react-practice/pull/2

**Comment by chucklien** [comment]
already resolved.
